<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>LeitostrapV7</AssemblyName>
    <RootNamespace>LeitostrapV7</RootNamespace>
    <ApplicationIcon>Leitostrap.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>false</PublishReadyToRun>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Leitostrap.png" />
    <Resource Include="Leitostrap.ico" />
    <Resource Include="Resources\Roblox.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\Lang\*.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Resources\Games FFlags\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
